module.exports = [
  require('./v001_initial_schema'),
  require('./v002_add_audit_logs'),
  require('./v003_add_policy_router_fields'),
  require('./v004_add_mcp_gateway_field'),
  require('./v005_add_missions_and_agent_runs'),
  require('./v006_add_approval_requests'),
  require('./v007_add_agent_run_events'),
  require('./v008_add_idempotency_keys'),
  require('./v009_add_semantic_layer_v02'),
  require('./v010_add_knowledge_gateway'),
  require('./v011_add_tool_calls_and_budgets'),
  require('./v012_add_debug_mode_to_categories'),
  require('./v013_add_allowed_categories_to_users'),
  require('./v014_add_category_to_sessions'),
  require('./v015_add_is_admin_to_users'),
  require('./v016_add_token_accounting'),
  require('./v017_add_category_complexity'),
  require('./v018_add_tokens_allocated_to_history'),
  require('./v019_add_suggested_questions_and_sort_index_to_categories'),
  require('./v020_rename_mcp_gateway_to_yandex_folder_id'),
  require('./v021_add_payment_orders'),
  require('./v022_add_user_context_generation_limits'),
  require('./v023_convert_category_input_limits_to_token_scale'),
  require('./v024_add_query_performance_indexes'),
  require('./v025_add_user_token_history_indexes')
];

